### PR TITLE
Add Excel file export. Refs #572

### PR DESCRIPTION
**Pull request by chigby**
Add a button to export the currently exportable tables into .xlsx format.

The UI is about as simple as possible and could possibly be improved, but I am not really familiar enough with the buttons and controls you have going so it might be inconsistent. Having one button for csv and one for excel could pretty easily be replaced with a dropdown or popup or something else to make it fit in better with what you have or just generally be more user-friendly.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Either the buttons as is or a dropdown would be fine with me. Dropdown might be trickier since the elements inside it have to be `<buttons>` and I'm not 100% sure how Bootstrap will handle that. Could also be done as a popover the way I did the saved reports dropdown. But I'm also fine with it as is!

**Comment by melinath** [comment]
Could just be a dropdown like toggl.

screen shot 2015-09-18 at 10 35 12 am

**Comment by melinath** [comment]
screen shot 2015-09-18 at 10 36 32 am

Or Google Docs. No need for buttons.

**Comment by harrislapiroff** [comment]
They need to be buttons because they're submitting a form, is why. :stuck_out_tongue_closed_eyes:

**Comment by harrislapiroff** [comment]
(Though the whole system that's going on with the form that navbar is a UX mess and should be restructured eventually. Maybe when we make it async though.)

**Comment by melinath** [comment]
Oh right. :-p

FWIW I am also getting weird flow on the order table.

screen shot 2015-09-18 at 10 39 32 am

**Comment by melinath** [comment]
I'ma give it a shot.e

**Comment by nmorduch** [comment]
looks good but when i tried to use it i got 

>Error response

>Error code 414.

>Message: Request-URI Too Long.

>Error code explanation: 414 = URI is too long..

**Comment by nmorduch** [comment]
But if it works (eg just wasn't working for me) :+1:

**Comment by melinath** [comment]
@nmorduch was that on the attendee view? Slash which browser?

**Comment by nmorduch** [comment]
orders, FF 40

**Comment by melinath** [comment]
So, I suspect that's probably due to a long querystring on the order view – from all the columns etc. – which would be a separate ticket. Could you try on the finances view?

**Comment by harrislapiroff** [comment]
Time to switch to POST? :|

**Comment by melinath** [comment]
so it would seem. but in a separate ticket.

**Comment by melinath** [comment]
http://thedailywtf.com/articles/HTTP-414-Way-Too-Fing-Long

attn @nmorduch especially :-) This is actually the first time I've ever seen a 414 error! Exciting times! I can't reproduce it myself, but I'm confident it has nothing to do with the excel download portion of this ticket. I'll open a new ticket for that issue.

**Comment by harrislapiroff** [comment]
OOC what is responsible for serving the 414? nginx? Django? Not the browser, I assume? Is this a server-side setting we can just change. Also, how long was the URI???

**Comment by melinath** [comment]
It's a server-side thing. http://stackoverflow.com/questions/1067334/how-to-set-the-allowed-url-length-for-a-nginx-request-error-code-414-uri-too

I had one that was 1043 characters long working fine. I'd have to work pretty hard to get over 2900 characters... I think we should be fine for now. But someone will break this someday.

**Pull request merged**
