### PR TITLE
Shorten Register button on dashboard

### PR DESCRIPTION
**Pull request by nmorduch**
Also remove Facebook button from dashboard.

### CODE REVIEW

**Comment by melinath** [comment]
@nmorduch why remove the facebook button?

**Comment by nmorduch** [comment]
Doesn't need to be on homepage and takes up a ton of space. Better imo to have it on the shop page, since that's where the event description is. Having it on the homepage seems a bit like there's not a description on the shop page.

**Comment by nmorduch** [comment]
Mehhh it's probably fine either way.

**Comment by melinath** [comment]
I wonder - what about just getting rid of that line of buttons altogether? And making the name link to the registration as well?

**Comment by nmorduch** [comment]
we never a/b tested, but buttons are helpful for people who don't think to click on things that don't scream link

**Comment by melinath** [comment]
I think the website and register buttons look pretty lonely now:

screen shot 2017-02-10 at 11 40 41 am

Adding the FB url back in would _help_, but also... people seem to do fine interacting with sites like Eventbrite, which does not have a separate "register" button.

screen shot 2017-02-10 at 11 40 04 am

**Comment by nmorduch** [comment]
I could be convinced.

Naomi I. Morduch Toubman
Little Weaver Web Collective
littleweaverweb.com

**Comment by melinath** [comment]
Closing in favor of #834.

**Pull request closed without merging**
