### PR TITLE
Salt in brambling

### LINKED ISSUE #767: Move deployment code into django-brambling
This includes making a fabfile and copying over the salt code from the dancerfly.com repo. And some additional documentation.

### LINKED ISSUE #768: Deploy staging server
Staging server would let us let people actually... REVIEW things. Without needing to figure out how to deploy the branch you're on.

### PR DESCRIPTION
**Pull request by melinath**
This branch moves all deployment-related code into django-brambling, obviating the dancerfly.com repository. Resolves #767. Also, because this is being tested on a staging server, resolves #768.

Remaining issues:

- [x] Fix compressor's sass compilation
- [x] Fix failing test
- [x] deploy once more from scratch

### CODE REVIEW

**Comment by chigby** [comment]
Is there documentation somewhere on what servers we are actually using for staging and production? This code is probably fine but I don't have enough information to try it out.

**Comment by melinath** [comment]
@chigby DigitalOcean. Login info is on lastpass.

**Comment by chigby** [comment]
Here's what happens when I run `$ fab -H dancerfly-staging deploy:master`:

```
[dancerfly-staging] Executing task 'deploy'
[dancerfly-staging] rsync_project: rsync  -pthrvz  --rsh='ssh -i /home/chigby/.ssh/id_rsa -p 22 ' pillar/ root@162.243.226.226:/srv/pillar/
[localhost] local: rsync  -pthrvz  --rsh='ssh -i /home/chigby/.ssh/id_rsa -p 22 ' pillar/ root@162.243.226.226:/srv/pillar/
sending incremental file list
rsync: change_dir "/home/chigby/lw/django-brambling//pillar" failed: No such file or directory (2)
```

**Comment by melinath** [comment]
@chigby fixed

**Comment by chigby** [comment]
Here's what I get now:

```
$ fab -H dancerfly-staging deploy:master
[dancerfly-staging] Executing task 'deploy'
[localhost] local: git clone git@github.com:littleweaver/dancerfly-pillar.git pillar
Cloning into 'pillar'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 10 (delta 1), reused 9 (delta 0), pack-reused 0
Receiving objects: 100% (10/10), 9.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
[dancerfly-staging] sudo: git fetch
[dancerfly-staging] sudo: git stash
[dancerfly-staging] out: No local changes to save
[dancerfly-staging] out: 

[dancerfly-staging] sudo: git checkout master
[dancerfly-staging] out: Already on 'master'
[dancerfly-staging] out: Your branch is up-to-date with 'origin/master'.
[dancerfly-staging] out: 

[dancerfly-staging] sudo: git reset --hard origin/master
[dancerfly-staging] out: HEAD is now at faf97f7 Added rsa private key for deployment.
[dancerfly-staging] out: 

[dancerfly-staging] sudo: git fetch
[dancerfly-staging] out: remote: Counting objects: 43, done.
[dancerfly-staging] out: remote: Compressing objects:   4% (1/21)   
[dancerfly-staging] out: remote: Compressing objects:   9% (2/21)   
[dancerfly-staging] out: remote: Compressing objects:  14% (3/21)   
[dancerfly-staging] out: remote: Compressing objects:  19% (4/21)   
[dancerfly-staging] out: remote: Compressing objects:  23% (5/21)   
[dancerfly-staging] out: remote: Compressing objects:  28% (6/21)   
[dancerfly-staging] out: remote: Compressing objects:  33% (7/21)   
[dancerfly-staging] out: remote: Compressing objects:  38% (8/21)   
[dancerfly-staging] out: remote: Compressing objects:  42% (9/21)   
[dancerfly-staging] out: remote: Compressing objects:  47% (10/21)   
[dancerfly-staging] out: remote: Compressing objects:  52% (11/21)   
[dancerfly-staging] out: remote: Compressing objects:  57% (12/21)   
[dancerfly-staging] out: remote: Compressing objects:  61% (13/21)   
[dancerfly-staging] out: remote: Compressing objects:  66% (14/21)   
[dancerfly-staging] out: remote: Compressing objects:  71% (15/21)   
[dancerfly-staging] out: remote: Compressing objects:  76% (16/21)   
[dancerfly-staging] out: remote: Compressing objects:  80% (17/21)   
[dancerfly-staging] out: remote: Compressing objects:  85% (18/21)   
[dancerfly-staging] out: remote: Compressing objects:  90% (19/21)   
[dancerfly-staging] out: remote: Compressing objects:  95% (20/21)   
[dancerfly-staging] out: remote: Compressing objects: 100% (21/21)   
[dancerfly-staging] out: remote: Compressing objects: 100% (21/21), done.
[dancerfly-staging] out: remote: Total 43 (delta 31), reused 31 (delta 22), pack-reused 0
[dancerfly-staging] out: Unpacking objects:   2% (1/43)   
[dancerfly-staging] out: Unpacking objects:   4% (2/43)   
[dancerfly-staging] out: Unpacking objects:   6% (3/43)   
[dancerfly-staging] out: Unpacking objects:   9% (4/43)   
[dancerfly-staging] out: Unpacking objects:  11% (5/43)   
[dancerfly-staging] out: Unpacking objects:  13% (6/43)   
[dancerfly-staging] out: Unpacking objects:  16% (7/43)   
[dancerfly-staging] out: Unpacking objects:  18% (8/43)   
[dancerfly-staging] out: Unpacking objects:  20% (9/43)   
[dancerfly-staging] out: Unpacking objects:  23% (10/43)   
[dancerfly-staging] out: Unpacking objects:  25% (11/43)   
[dancerfly-staging] out: Unpacking objects:  27% (12/43)   
[dancerfly-staging] out: Unpacking objects:  30% (13/43)   
[dancerfly-staging] out: Unpacking objects:  32% (14/43)   
[dancerfly-staging] out: Unpacking objects:  34% (15/43)   
[dancerfly-staging] out: Unpacking objects:  37% (16/43)   
[dancerfly-staging] out: Unpacking objects:  39% (17/43)   
[dancerfly-staging] out: Unpacking objects:  41% (18/43)   
[dancerfly-staging] out: Unpacking objects:  44% (19/43)   
[dancerfly-staging] out: Unpacking objects:  46% (20/43)   
[dancerfly-staging] out: Unpacking objects:  48% (21/43)   
[dancerfly-staging] out: Unpacking objects:  51% (22/43)   
[dancerfly-staging] out: Unpacking objects:  53% (23/43)   
[dancerfly-staging] out: Unpacking objects:  55% (24/43)   
[dancerfly-staging] out: Unpacking objects:  58% (25/43)   
[dancerfly-staging] out: Unpacking objects:  60% (26/43)   
[dancerfly-staging] out: Unpacking objects:  62% (27/43)   
[dancerfly-staging] out: Unpacking objects:  65% (28/43)   
[dancerfly-staging] out: Unpacking objects:  67% (29/43)   
[dancerfly-staging] out: Unpacking objects:  69% (30/43)   
[dancerfly-staging] out: Unpacking objects:  72% (31/43)   
[dancerfly-staging] out: Unpacking objects:  74% (32/43)   
[dancerfly-staging] out: Unpacking objects:  76% (33/43)   
[dancerfly-staging] out: Unpacking objects:  79% (34/43)   
[dancerfly-staging] out: Unpacking objects:  81% (35/43)   
[dancerfly-staging] out: Unpacking objects:  83% (36/43)   
[dancerfly-staging] out: Unpacking objects:  86% (37/43)   
[dancerfly-staging] out: Unpacking objects:  88% (38/43)   
[dancerfly-staging] out: Unpacking objects:  90% (39/43)   
[dancerfly-staging] out: Unpacking objects:  93% (40/43)   
[dancerfly-staging] out: Unpacking objects:  95% (41/43)   
[dancerfly-staging] out: Unpacking objects:  97% (42/43)   
[dancerfly-staging] out: Unpacking objects: 100% (43/43)   
[dancerfly-staging] out: Unpacking objects: 100% (43/43), done.
[dancerfly-staging] out: From https://github.com/littleweaver/django-brambling
[dancerfly-staging] out:    7e5e781..cdd4f37  salt-in-brambling -> origin/salt-in-brambling
[dancerfly-staging] out:  + 023fa03...b46e211 django-1.8 -> origin/django-1.8  (forced update)
[dancerfly-staging] out: 

[dancerfly-staging] sudo: git stash
[dancerfly-staging] out: No local changes to save
[dancerfly-staging] out: 

[dancerfly-staging] sudo: git checkout master
[dancerfly-staging] out: Switched to branch 'master'
[dancerfly-staging] out: Your branch is up-to-date with 'origin/master'.
[dancerfly-staging] out: 

[dancerfly-staging] sudo: git reset --hard origin/master
[dancerfly-staging] out: HEAD is now at fa918f3 Merge branch 'pyflakes-in-tests'
[dancerfly-staging] out: 

[dancerfly-staging] sudo: chmod -R a+rw /var/www/django-brambling
[dancerfly-staging] sudo: rm -rf /srv/salt
[dancerfly-staging] sudo: mkdir /srv/salt
[dancerfly-staging] sudo: cp -R salt/* /srv/salt
[dancerfly-staging] out: cp: cannot stat ‘salt/*’: No such file or directory
[dancerfly-staging] out: 


Fatal error: sudo() received nonzero return code 1 while executing!

Requested: cp -R salt/* /srv/salt
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "cd /var/www/django-brambling >/dev/null && cp -R salt/* /srv/salt"

Aborting.
Disconnecting from root@162.243.226.226... done.
```

**Comment by melinath** [comment]
@chigby you're deploying master. That doesn't work because this branch hasn't been merged into master yet, so there's no configuration (i.e. no salt dir) included.

**Comment by melinath** [comment]
you have to do `fab -H dancerfly-staging deploy:salt-in-brambling` for now.

**Comment by chigby** [comment]
@melinath I tried to deploy again (correct branch this time! :smiley:) and it failed cryptically, but I think the staging server is running out of memory while trying to install requirements? `dmesg | tail` shows:

```
[297778.312384] Out of memory: Kill process 12673 (cc1plus) score 460 or sacrifice child
[297778.312451] Killed process 12673 (cc1plus) total-vm:270460kB, anon-rss:230016kB, file-rss:284kB
```

**Comment by melinath** [comment]
Yeah, I think that's what's happening as well :-p I guess bump the server size and try again

**Comment by harrislapiroff** [comment]
Is it possible there's a leak somewhere? Some process that gets started during deployment and never terminated or something?

**Comment by melinath** [comment]
salt just takes a lot of memory.

**Comment by harrislapiroff** [comment]
Also, I'm worried that the server wants us to solve this problem by sacrificing a child.

**Comment by chigby** [comment]
Bumped us from 512MB to 1GB.

**Comment by chigby** [comment]
Seems to have worked. I'm merging this.

**Pull request merged**
