### PR TITLE
Add Strict-Transport-Security header to nginx config.

### PR DESCRIPTION
**Pull request by chigby**
Suggested in #775.

### CODE REVIEW

**Comment by melinath** [comment]
@chigby is there an advantage to doing things this way rather than using SecurityMiddleware (which also adds some other measures at the same time)?

**Comment by melinath** [comment]
(I also want to make sure that if we do go with this PR we don't lose sight of the other concerns brought up in #775 and not addressed here. I'm not saying they necessarily _should_ be addressed here. Just don't want to forget them.)

**Comment by chigby** [comment]
@melinath From the SecurityMiddleware docs:

> If your deployment situation allows, it’s usually a good idea to have your front-end Web server perform the functionality provided by the SecurityMiddleware. That way, if there are requests that aren’t served by Django (such as static media or user-uploaded files), they will have the same protections as requests to your Django application.

**Comment by melinath** [comment]
@chigby ah, yes. okay. We should be sure then to also add the other cases that SecurityMiddleware would normally handle.

**Comment by chigby** [comment]
Yes, this is a good plan. I'm working on another branch/future PR with the other security improvements from #796, the security middleware, SSL site tester results, and other sources.

**Comment by melinath** [comment]
Sweet, look forward to that branch :-)

**Pull request merged**
