### PR TITLE
Dwolla updates

### PR DESCRIPTION
**Pull request by melinath**
Was hoping to test #659, but had to make some [updates to our dwolla handling](https://discuss.dwolla.com/t/action-required-oauth-redirect-uri-must-be-configured-in-application-settings/1605) first. Those should be done with this PR.

### CODE REVIEW

**Comment by melinath** [comment]
Okay, that makes the tests runnable. We'll only have to generate new tokens if/when the api changes.

**Comment by chigby** [comment]
I feel like something weird is happening with my setup, because the test fails with: 

```
FAIL: test_dwolla_charge__user (brambling.tests.integration.test_dwolla.DwollaChargeTestCase)
[...]
AssertionError: u'Order 000001 for Test event' != 'Order 000041 for Test event'
```

**Comment by chigby** [comment]
Or should I be recording my own vcr cassette?

**Comment by melinath** [comment]
@chigby No, you should be able to use the same cassette. My guess is that you're running the whole test suite, whereas I only ran the one test, so the order code is different... though that shouldn't be stored anywhere... hmm.

**Comment by melinath** [comment]
Oh, it's because the value on the left is charge['notes'].

**Comment by melinath** [comment]
I'm gonna switch to a deterministic order code.

**Pull request merged**
