### PR TITLE
Org creation

### PR DESCRIPTION
**Pull request by melinath**
Set up org creation directly from event creation. I feel like there must be a ticket open for this but I can't find it right now.

Users without an org will only have the option to create. Other users default to existing org but can toggle between that and creating a new org.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
If City/State are not on the creation form, they shouldn't be required on the update form: 

screen shot 2015-10-03 at 5 23 30 pm

Otherwise the update form is unsubmittable by default.

**Comment by melinath** [comment]
I'd be fine making them optional, I think?

**Comment by harrislapiroff** [comment]
:+1:

**Comment by harrislapiroff** [comment]
Seems to work. The UI isn't perfect, but it's good enough and cleaning it up will probably rely on some better ractive components/dropdowns. COOL!

**Comment by harrislapiroff** [comment]
:cool: :sunglasses:

**Pull request merged**
