### PR TITLE
closed #366 invite table overflow

### LINKED ISSUE #366: Suboptimal invite table overflow
At certain window sizes, the event editor invite table displays suuuuuper awkwardly. It might be a function of the invitee having a really long email address.

screen shot 2015-02-24 at 6 18 24 pm

### PR DESCRIPTION
**Pull request by nmorduch**
Don't trust the diff. Literally just wrapped that table in a table-responsive

### CODE REVIEW

**Comment by melinath** [comment]
This is definitely an improvement, but the behavior is a little weird... specifically, when I scroll, the title of the table also scrolls (and disappears). Maybe it could be moved out and turned into a `<label>` or `<h#>`?

screen shot 2015-03-23 at 5 05 58 pm

**Comment by nmorduch** [comment]
I'm just going to remove the table header altogether. I don't think it adds any information.

**Comment by nmorduch** [comment]
Also, please email me any comments at boop@boop.com :)

**Comment by melinath** [comment]
Good call. Nice!

**Pull request merged**
