### PR TITLE
Dwolla fixes

### PR DESCRIPTION
**Pull request by melinath**
Resolved a couple of bugs related to (dwolla) payment processing.

Specifically #370 and #386.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Is this ready?

**Comment by melinath** [comment]
Yes

**Comment by harrislapiroff** [comment]
I got this :(

screenshot 2015-03-04 13 36 18

**Comment by melinath** [comment]
@harrislapiroff I almost guarantee that your user had old dwolla data stored. (i.e. without a refresh token) You'll need to go into the admin because #391

**Comment by harrislapiroff** [comment]
I'll check that shortly.

**Comment by harrislapiroff** [comment]
Okay, this is impossible for me to fully test because I just keep getting insufficient funds messages, but it's at least working to the point of failed checkout, so I guess that'll have to be good enough. Merging.

**Pull request merged**
