### PR TITLE
Implemented an item delete view. Resolved #533.

### LINKED ISSUE #533: Item Deletion
There's currently no way to delete an item, but there should be.

### PR DESCRIPTION
**Pull request by melinath**
I know that we "shouldn't" use get for deletion views, but I think this is a case of practicality beats purity. Getting a browser to *actually* issue a POST or DELETE for a deletion is a PITA. :-p This is a simple implementation that will let organizers delete items whenever they want.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Wait, all you have to do to fire a POST is make a form with a button! I would somewhat strongly advocate for that.

**Comment by harrislapiroff** [comment]
For the record that is also how Django's generic deleteviews do it and it protects the user in a host of ways including CSRF. (I can't maliciously send a user a link that will delete their data.)

**Comment by melinath** [comment]
The button is inside a form already! I can't create a form in a form.

**Comment by harrislapiroff** [comment]
Then move it after the form. Upon consideration, I would actually call this a pretty severe security hole.

**Comment by melinath** [comment]
If it weren't then yeah I would've done that. And yeah, of course I could work around this by, like, dynamically creating a form or changing the action of the form and deleting all the fields, but that level of weirdness just seems bizarre.

**Comment by melinath** [comment]
If it's after the form it doesn't flow correctly with the save button. Unless I hook that up with JS to submit the form properly.

**Comment by melinath** [comment]
Which would be less weird, I suppose.

**Comment by harrislapiroff** [comment]
Any solution is better than letting me, a malicious dance event competitor, send you a link which triggers a permanent delete of your valuable attendee data.

**Comment by harrislapiroff** [comment]
(Or letting a browser think it's OK to hit that URL over and over again, though in this case that's less critical since that URL will only work once anyway.)

**Comment by melinath** [comment]
I'll fix this in a bit.

**Comment by harrislapiroff** [comment]
I'm pretty sure I have javascript in the repo already for triggering submission of another form based on clicking a button elsewhere, but I can't remember where.

**Comment by melinath** [comment]
It's not that hard. I can write that JS.

**Comment by melinath** [comment]
@harrislapiroff fixed

**Comment by chigby** [comment]
I got a little squeamish about having a delete button without a confirmation box, so I added one. Hope my little explanation is correct, but if anyone wants to change the wording or something, they should.

**Comment by melinath** [comment]
I almost put in a confirmation box but then I was too lazy :-p

**Comment by harrislapiroff** [comment]
:+1: to confirmation modals for deletion

plus it solves the nested forms issue :stuck_out_tongue_closed_eyes:

**Comment by melinath** [comment]
I already solved the nested forms issue! :-p

**Comment by harrislapiroff** [comment]
Now your solution is excessive!

**Comment by melinath** [comment]
UGH.

**Comment by melinath** [comment]
image

**Comment by melinath** [comment]
fed-up-with-this-world-o

**Comment by melinath** [comment]
done

**Comment by melinath** [comment]
screen shot 2015-09-16 at 1 59 25 pm

**Pull request merged**
