### PR TITLE
Updated event summary to include refund finances and differentiate between pending and completed payments.

### PR DESCRIPTION
**Pull request by melinath**
@nmorduch I think this resolves the event summary page display for now - did you want to include the order summary improvements as part of this ticket / include changes there? The data should now all be available. If there's anything missing let me know.

### CODE REVIEW

**Comment by nmorduch** [comment]
Before I do this, does it work with the new internationalization?

**Comment by melinath** [comment]
Yes, it should. Stripe charges use the event's currency, which was already changeable. The only "internationalization" that I did was actually displaying the correct country and currency on the event settings page.

**Comment by melinath** [comment]
So this works as well as what we already had.

**Comment by nmorduch** [comment]
Closes #292

**Comment by nmorduch** [comment]
I did this using rebase in the command line and the commit went onto master but github thinks this branch is not merged. Did I do something wrong? I normally just merge using the button that says merge, but I didn't want the merge commit that comes with that.

**Comment by melinath** [comment]
If you're merging from the command line, you do `git merge <branch> --no-ff` from the master branch. This makes a merge commit to show that a branch was merged. Rebase just sticks the branch on the end of the master branch as if it had always been there. If you then merge without --no-ff, the master fast-forwards.

Generally speaking, we want to have merge commits.

**Comment by nmorduch** [comment]
But if we always have a new branch for every little thing, then that's a million merge commits. 

What should I do to remedy this now?

**Comment by melinath** [comment]
Meh, just delete the branch.

**Pull request closed without merging**
