### PR TITLE
Receipt redesign

### PR DESCRIPTION
**Pull request by melinath**
I've tried to clean up and clarify receipts / order attendees. I believe this branch will close at least the following tickets:

* [x] #287 Better interface for marking checks as paid.
* [x] #398 Better icon for refund, with help text
* [x] #402 Display multiple transactions on shopping summary page 
* [x] #393 Use parentheses for negative in order summary 
* [x] #290 Refunded items display in order summary 
* [x] #326 Payment form UI
* [x] Emails
* [x] #505 Only apply discounts to current cart.
* [x] Discounts (do they actually get calculated right?)

This isn't quite done. The receipt views still need another quick pass, and this needs to be integrated into emails (possibly touching on #484 Thunderbird marking emails as spam).

### CODE REVIEW

**Comment by melinath** [comment]
Attendees whose passes have been refunded will not be accessible to edit from the summary – but that will be resolved by the branch which removes item categories.

**Comment by melinath** [comment]
@harrislapiroff This is ready for review. I think you'll like it? I hope!

**Comment by nmorduch** [comment]
Can these not be buttons? It's confusing that the change on hover but aren't clickable. Maybe labels instead?

**Comment by nmorduch** [comment]
Ohhhhh because it's the same design for attendees as organizers. I think that should be changed though, before merging.

**Comment by nmorduch** [comment]
What is the " Better interface for marking checks as paid."?

**Comment by melinath** [comment]
It would be pretty trivial to switch those to labels for attendees - that template block is overridden completely on the organizer side. Feel free to make that change!

Better interface is having actual buttons instead of organizers having to know they can click on what looks like a piece of text. I'm sure it could be improved further, though. Maybe a tooltip?

**Comment by nmorduch** [comment]
Tooltips are pretty eh for touch screen users :/

**Comment by melinath** [comment]
The organizer interface is not really intended to be optimized for mobile.

**Comment by melinath** [comment]
See also: the table views.

**Comment by nmorduch** [comment]
Eventually I'd live everything to work for all devices though? e.g. ipads are quite reasonable

**Comment by melinath** [comment]
Ah, fair enough. Switching to buttons is an improvement and all I want to do in this PR. If we want to do more later we can just keep the other ticket open.

**Comment by nmorduch** [comment]
:+1:

**Comment by harrislapiroff** [comment]
Agree with discussion here. FWIW, IMO better interface in #287 means be not having to go to a record's detail view to mark a check as paid, since organizers are likely to be doing that in bulk. But that conversation already happened on the ticket.

**Comment by harrislapiroff** [comment]
This looks nice, but for a future redesign, I think we've outgrown sharing the templates between the order view from the attendee side and the order view from the organizer side. The purpose of each view is different. For the organizer it should be as efficient/compact as possible and can rely on the organizer's familiarity with the interface over time since they'll be seeing it a lot. For the attendee it should be more verbose, as it is in this redesign.

**Comment by harrislapiroff** [comment]
NICE WORK ON THE PAYMENT ACCORDION

**Comment by harrislapiroff** [comment]
Although, maybe in a future ticket, we should mimic other checkout processes such that if you have a saved card, it just displays that and then provides a nearby button/link to use a different card and swap out the form. I think it'd be nice if credit card was a single panel.

But seriously it looks good.

**Comment by harrislapiroff** [comment]
Agree with Naomi that unclickable buttons are extremely confusing. It feels like I'm supposed to click that to confirm my registration.

**Comment by harrislapiroff** [comment]
If you address those things above, either by polishing the UI now or creating future tickets, I think this is otherwise good to go, @melinath.

**Comment by melinath** [comment]
1. Oh right, that is what we'd talked about with the better interface for check confirmation. Whoops! Still, I think this is an improvement...

2. +1 on splitting the templates for receipts. I almost did that here, but didn't relish the idea of revamping that interface completely on top of everything else...

3. yay I'm glad you like it!

The only thing I would want to maybe not open a new ticket for is the unclickable button issue. I guess a quick fix would be to make the button disabled on the customer side of things...? Slash, do you think it's safe to merge this without fixing that and then get it in a later ticket?

**Comment by melinath** [comment]
I don't know how long we'd want to leave that.

**Comment by harrislapiroff** [comment]
I think disabled buttons would still be confusing since those still have a different cursor. Maybe just fix it here if it's quick though? Can you use an `{% if %}` and just swap it to a message or label or [colored text](http://getbootstrap.com/css/#helper-classes-colors)?

**Comment by melinath** [comment]
screen shot 2015-05-14 at 11 47 54 am

**Comment by harrislapiroff** [comment]
Looks good. I'm happy for you to merge if you're happy with it!

**Pull request merged**
