### PR TITLE
Order summary

### PR DESCRIPTION
**Pull request by nmorduch**
Makes the order summary page feel a little more receipt-like. You should look at it and see if it makes sense to you. It will no doubt need changes as we go into the multiple orders thing, but a lot of the styles will be useful.

### CODE REVIEW

**Comment by nmorduch** [comment]
@harrislapiroff can you look at this too?

**Comment by melinath** [comment]
I rebased this branch onto the latest master... it looks like there were some template variable name changes that made this version of the template no longer work correctly. But overall I do like it, I think. It'll need a bit of work to bring it up to date.

**Comment by melinath** [comment]
This might actually be something broken due to a lack of internationalization support after all.

**Comment by melinath** [comment]
Yeah, littleweaver/django-zenaida@d506bba5c0597fcdd292f8af3391517fc1e74b1f fixed the issues I was seeing. I think I like this more, but it does have less information, but that might be okay. I'd be interested in what @harrislapiroff thinks.

**Comment by melinath** [comment]
It's a little weird to me that the cost is in a completely different place than the payments / refunds. I like the items being grouped on the side, but maybe they shouldn't list prices?

**Comment by nmorduch** [comment]
How about this? When transactions become self-aware, we should:

- Remove prices from the Attendee in formation
- Make each transaction have a dropdown that says what things were bought for how much and for whom.

**Comment by melinath** [comment]
Remaining dev work related to this: RefundView needs to check whether an order is fully or partially refunded and mark it appropriately. I think? Or should we just be annotating the Order model more aggressively with payments received and total refunds and not have status there at all?

Also, manual payments should probably mark any current cart as paid and attach the items to the payment. Manual payment page should also display currently-owed amount (and default the payment amount to that.)

**Comment by nmorduch** [comment]
@melinath is this currently waiting on more development or do you want it merged?

**Comment by nmorduch** [comment]
As far as I'm concerned this can be merged, but @harrislapiroff should be the one to review the python.

**Comment by melinath** [comment]
@nmorduch I thought there was still more design work on this.

**Comment by melinath** [comment]
That's why i assigned it to you, not for review, IIRC. Though I probably should have said that with words. :-p

**Comment by nmorduch** [comment]
I think it should be merged and i can do additional work on a separate pull request.

**Comment by harrislapiroff** [comment]
I think it would be nice to have payment information associated with each item (at minimum display a status indicator for "Unpaid", "Paid", or "Refunded", but this is definitely very nice. Merging.

Another thought: ultimately we might want separate views for "Your items" and "Your receipts"

**Pull request merged**
