### PR TITLE
Added table count. Resolved #429.

### LINKED ISSUE #429: Add result count to model tables
It would be useful to have a result count (out of total, if filtered) display somewhere on the model table pages.

### PR DESCRIPTION
**Pull request by harrislapiroff**

### CODE REVIEW

**Comment by melinath** [comment]
From a design perspective, it's a little weird that the baseline doesn't match up with the form elements. I'm guessing we're holding off on that?

From a functionality perspective, the link provided on the orders page to a full list of orders doesn't actually do so, because the default behavior for the orders page (if no parameters are provided) is to filter out in progress / refunded orders. This may be obviated somewhat once #385 lands - or we might end up having a similar setup. I think it would be nice to have a way to explicitly say what the "full listing" url would look like?

**Comment by harrislapiroff** [comment]
Yeah, I don't wanna make too many changes to the sass before #430 is resolved and I think the best aesthetic approach would be to use a navbar (as noted in the comment) that was closer to bootstrap's default navbar.

Functionality-wise, you're right. Can you think of the best way to build this?

**Comment by melinath** [comment]
I'll take a stab at it and then bounce this back to you.

**Comment by melinath** [comment]
Unless you want to do it.

**Comment by harrislapiroff** [comment]
FWIW what occurred to me was generating a version of the filterset form that has all hidden fields and blanks them all.

**Comment by harrislapiroff** [comment]
Nah, you can do it however you think is good. I think you'll do a better job.

**Comment by melinath** [comment]
Yeah, that was what I went with. Had to open gregmuellegger/django-floppyforms#145, but I was able to work around it in the meantime.

This change has introduced some new issues with UI, so it might be worth just fixing this as a whole... bouncing back to you.

**Comment by harrislapiroff** [comment]
I made it palatable. I'll make a ticket to clean up the UI later. Merging.

**Pull request merged**
