### PR TITLE
Ticket/204 - Dwolla refresh token handling

### PR DESCRIPTION
**Pull request by melinath**
This includes what should be full support for dwolla refresh tokens, thus closing #204. It turns out that stripe access tokens don't (currently, at least) expire, so we're good there.

I want to wait until this is merged before I do #330 and #335, since they're in a similar vein.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
When visiting an event page I get this traceback:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/harris-dance-weekend/order/summary/

Django Version: 1.7.4
Python Version: 2.7.6
Installed Applications:
('brambling',
 'grappelli',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'zenaida',
 'zenaida.contrib.hints',
 'floppyforms',
 'django_filters',
 'daguerre',
 'debug_toolbar.apps.DebugToolbarConfig',
 'template_timings_panel',
 'zenaida.contrib.feedback',
 'talkback')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'talkback.middleware.TalkbackMiddleware')


Traceback:
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/Users/harris/Projects/Clients/Little Weaver/django-brambling/brambling/views/orders.py" in dispatch
  258.         return super(OrderMixin, self).dispatch(request, *args, **kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/Users/harris/Projects/Clients/Little Weaver/django-brambling/brambling/views/orders.py" in get
  754.             self.get_forms()
File "/Users/harris/Projects/Clients/Little Weaver/django-brambling/brambling/views/orders.py" in get_forms
  829.         if self.event.uses_dwolla():
File "/Users/harris/Projects/Clients/Little Weaver/django-brambling/brambling/models.py" in uses_dwolla
  389.         return self.connected_to_dwolla_test()
File "/Users/harris/Projects/Clients/Little Weaver/django-brambling/brambling/models.py" in connected_to_dwolla_test
  145.             self.dwolla_test_refresh_token_expires < timezone.now() and

Exception Type: TypeError at /harris-dance-weekend/order/summary/
Exception Value: can't compare datetime.datetime to NoneType
```

**Comment by harrislapiroff** [comment]
Is this maybe an issue with migrating accounts from old dwolla auth to new?

**Comment by melinath** [comment]
Yeah, probably.

**Comment by harrislapiroff** [comment]
When disconnecting:

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/harris-dance-weekend/edit/

Django Version: 1.7.4
Python Version: 2.7.6
Installed Applications:
('brambling',
 'grappelli',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'zenaida',
 'zenaida.contrib.hints',
 'floppyforms',
 'django_filters',
 'daguerre',
 'debug_toolbar.apps.DebugToolbarConfig',
 'template_timings_panel',
 'zenaida.contrib.feedback',
 'talkback')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'talkback.middleware.TalkbackMiddleware')


Traceback:
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/views/generic/edit.py" in post
  230.         return super(BaseUpdateView, self).post(request, *args, **kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/views/generic/edit.py" in post
  173.             return self.form_valid(form)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/views/generic/edit.py" in form_valid
  149.         self.object = form.save()
File "/Users/harris/Projects/Clients/Little Weaver/django-brambling/brambling/forms/organizer.py" in save
  140.         instance = super(EventForm, self).save()
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/forms/models.py" in save
  455.                              construct=False)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/forms/models.py" in save_instance
  103.         instance.save()
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/base.py" in save
  589.                        force_update=force_update, update_fields=update_fields)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/base.py" in save_base
  617.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/base.py" in _save_table
  679.                                       forced_update)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/base.py" in _do_update
  723.         return filtered._update(values) > 0
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/query.py" in _update
  600.         return query.get_compiler(self.db).execute_sql(CURSOR)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  1004.         cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  775.             sql, params = self.as_sql()
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in as_sql
  969.                 val = field.get_db_prep_save(val, connection=self.connection)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/fields/__init__.py" in get_db_prep_save
  627.                                       prepared=False)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/fields/__init__.py" in get_db_prep_value
  1290.             value = self.get_prep_value(value)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/fields/__init__.py" in get_prep_value
  1269.         value = super(DateTimeField, self).get_prep_value(value)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/fields/__init__.py" in get_prep_value
  1171.         return self.to_python(value)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/fields/__init__.py" in to_python
  1252.             params={'value': value},

Exception Type: ValidationError at /harris-dance-weekend/edit/
Exception Value: [u"'' value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format."]
```

(Looking into now.)

**Comment by melinath** [comment]
the datetime fields need to be set to None in clear_dwolla_fields(), not `''`

**Comment by harrislapiroff** [comment]
Bouncing back to @melinath for a final review.

**Pull request merged**
