### PR TITLE
Item creation ui

### PR DESCRIPTION
**Pull request by harrislapiroff**
screenshot 2015-05-27 14 10 33

### CODE REVIEW

**Comment by harrislapiroff** [comment]
screenshot 2015-05-27 15 26 46

**Comment by harrislapiroff** [comment]
Okay, I think this is ready for review now.

**Comment by harrislapiroff** [comment]
There's room for improvement, especially with the image widgets, but that might be best saved for another ticket.

**Comment by melinath** [comment]
There's a weird thing that happens right between md and lg sizes...

screen shot 2015-05-27 at 11 45 35 pm

**Pull request merged**
