### PR TITLE
Organizer filter views

### PR DESCRIPTION
**Pull request by melinath**
Improvements to organizer filter views. Corrected CSV response generation to *actually* use the same table and implemented search.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
I'm a little concerned that putting the loupe button on the far side of the change columns and filter buttons is confusing. Is it okay if I move it next to the search bar?

**Comment by harrislapiroff** [comment]
I'm also a little concerned that this form might have some unexpected behavior. For instance, if I click "Change columns and filters", make some changes, press "Cancel", then enter a search term and press the loupe, the changes I supposedly cancelled will take effect.

**Comment by harrislapiroff** [comment]
Maybe I should just merge this as is and do a UI cleanup on another branch...

**Comment by melinath** [comment]
I'm okay with you moving the loupe. But I think I do prefer the UI cleanup as a separate branch, potentially.

**Comment by harrislapiroff** [comment]
:+1:

**Comment by harrislapiroff** [comment]
Also, if I enter search terms or change the filters, don't submit, and then press download CSV, it'll download a filtered CSV. There's a lot of potential UI failure points in making this a single form. I'll think about how to best break it up for another ticket.

**Comment by harrislapiroff** [comment]
@melinath Bouncing back to you for a final check. Merge if it's ready.

**Comment by melinath** [comment]
Looks fine to me.

**Pull request merged**
