### PR TITLE
Organizations

### PR DESCRIPTION
**Pull request by melinath**
The functionality should all be there, but we definitely still need to have a UI pass. Navigation especially.

Ticket #300 and #301.

* [x] Find out from current events what they would like their organization name and URL to be. _(Stephen)_
* [x] Fix [organization payment table display bug](https://github.com/littleweaver/django-brambling/pull/447#issuecomment-91869308) _(Stephen)_
* [x] [Make it easy to access the update organization info view](https://github.com/littleweaver/django-brambling/pull/447#issuecomment-91870121) (esp. payment methods) as an event organizer from the event pages _(Harris)_
* [x] [Demote organizations on the homepage](https://github.com/littleweaver/django-brambling/pull/447#issuecomment-91870875). _(Harris)_ - I took a stab at this (Stephen)
* [x] Make shop page accessible [even after purchasing](https://github.com/littleweaver/django-brambling/pull/447#issuecomment-91871197) _(Stephen)_
* [x] [Checkout FieldError](https://github.com/littleweaver/django-brambling/pull/447#issuecomment-91871591) _(Stephen)_

### CODE REVIEW

**Comment by melinath** [comment]
Once this is merged / maybe as part of this PR, we should send new receipts to folks who have orders for events that haven't happened yet, with an explanation of what's going on.

**Comment by harrislapiroff** [comment]
What's the necessity of new receipts?

**Comment by harrislapiroff** [comment]
I ask because I want to avoid sending such an email, if necessary. IMO this a change dance event attendees should not have to care about or notice. If this is about old links not resolving, I think a better solution would be for us to create redirects for those old links.

**Comment by melinath** [comment]
Mmm. Yeah, we could probably do that instead.

**Comment by harrislapiroff** [comment]
Before we deploy this, can we ask all active events what they'd like their organization URLs to be? That way we can set up the URLs and maybe specific redirects for the currently active events (assuming the org URLs don't conflict with the old event URLs).

**Comment by harrislapiroff** [comment]
Organization form not reflecting active Stripe (live) connection:

screenshot 2015-04-11 11 22 59
screenshot 2015-04-11 11 22 57

**Comment by harrislapiroff** [comment]
It's very difficult to get to editing organization info from an event. Say I'm an event organizer:

1. I go through the checkout process to test it.
2. I realize that I want to add a payment type.
3. I click on manage event, conveniently located in the corner of the screen.
4. ?????????

This requires a UI fix. I'll try to think of something.

**Comment by harrislapiroff** [comment]
I am also somewhat concerned that it is possible an organization may want different payment methods for different events, but maybe that's an issue for another day. Worst-case, we can spin up multiple organizations for them.

**Comment by harrislapiroff** [comment]
Like on GitHub with Repositories, the primary object that people will be concerned with when browsing Dancerfly will be Events. Organizations should be demoted in the visual hierarchy on the dashboard. The most common cases to optimize for are attendees who have no organizations an organizers who have only one. (They should moved to a less prominent location, given a design that doesn't make them look like events so as not to confuse, and specifically given a slighter design that can be easily ignored).

**Comment by harrislapiroff** [comment]
A thought: This PR makes me wish we had a `develop` or major version branch. I'd be happy to merge this once it's functional, except that I don't really want to deploy it with the current UI.

**Comment by harrislapiroff** [comment]
I can no longer return to the shop page once I've purchased some items, making multiple purchases impossible.

**Comment by harrislapiroff** [comment]
Field error during attempted checkout with payment method check:

```pytb
Environment:


Request Method: POST
Request URL: http://localhost:8000/triple-dance-weekend/triple-dance-weekend/order/summary/

Django Version: 1.7.4
Python Version: 2.7.6
Installed Applications:
('brambling',
 'grappelli',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'zenaida',
 'zenaida.contrib.hints',
 'floppyforms',
 'django_filters',
 'daguerre',
 'debug_toolbar.apps.DebugToolbarConfig',
 'template_timings_panel',
 'talkback')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'talkback.middleware.TalkbackMiddleware')


Traceback:
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/Users/harris/Projects/Clients/Little Weaver/django-brambling/brambling/views/orders.py" in dispatch
  264.         return super(OrderMixin, self).dispatch(request, *args, **kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/Users/harris/Projects/Clients/Little Weaver/django-brambling/brambling/views/orders.py" in post
  814.                                  secure=self.request.is_secure())
File "/Users/harris/Projects/Clients/Little Weaver/django-brambling/brambling/mail.py" in send_order_alert
  76.                                    Q(editor_events=order.event)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  92.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/query.py" in filter
  691.         return self._filter_or_exclude(False, *args, **kwargs)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/query.py" in _filter_or_exclude
  709.             clone.query.add_q(Q(*args, **kwargs))
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/query.py" in add_q
  1331.         clause, require_inner = self._add_q(where_part, self.used_aliases)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/query.py" in _add_q
  1353.                     current_negated)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/query.py" in _add_q
  1358.                     current_negated=current_negated, connector=connector)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/query.py" in build_filter
  1182.         lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/query.py" in solve_lookup_type
  1120.         _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/query.py" in names_to_path
  1427.             self.raise_field_error(opts, name)
File "/Users/harris/.virtualenvs/brambling/lib/python2.7/site-packages/django/db/models/sql/query.py" in raise_field_error
  1433.                          "Choices are: %s" % (name, ", ".join(available)))

Exception Type: FieldError at /triple-dance-weekend/triple-dance-weekend/order/summary/
Exception Value: Cannot resolve keyword 'owner_events' into field. Choices are: attendee, cards, confirmed_email, created_timestamp, dance_styles, default_card, default_card_id, dietary_restrictions, dismissed, dwolla_access_token, dwolla_access_token_expires, dwolla_refresh_token, dwolla_refresh_token_expires, dwolla_test_access_token, dwolla_test_access_token_expires, dwolla_test_refresh_token, dwolla_test_refresh_token_expires, dwolla_test_user_id, dwolla_user_id, editor_events, editor_orgs, ef_avoid, ef_cause, email, feedbackitem, given_name, groups, home, home_id, housing_prefer, id, invite, is_active, is_superuser, last_login, logentry, middle_name, modified_directly, name_order, order, other_needs, owner_orgs, password, person_avoid, person_prefer, phone, stripe_customer_id, stripe_test_customer_id, surname, transaction, user_permissions
```

**Comment by melinath** [comment]
@harrislapiroff just to clarify, I assigned this to you in part in the hopes that you could do a UI cleanup pre-merge.

**Comment by harrislapiroff** [comment]
@melinath's links to org updating from the event updating are good enough for now. I'm gonna make a basic UI pass and bounce it back to you, then open tickets for improving update views on both interfaces.

**Comment by harrislapiroff** [comment]
Okay, I feel all right about merging this. Leaving the final pass to you @melinath.

**Comment by melinath** [comment]
I think this is ready to merge now, but we need to wait until we hear back from folks about their org names before we push it live.

**Pull request merged**
