### PR TITLE
Ticket/203

### PR DESCRIPTION
**Pull request by melinath**
This includes pull request #303 and should probably be merged separately and afterwards.

This pull request also fixes some issues with dwolla & stripe payment.

It would be nice to have a go-through of the UI as part of this pull request to add appropriate notices in places as to whether an event is a test event or a live event. For example, would be nice to have something on the event settings page. It would also potentially be good to only warn about insecure connections on live event pages, and only provide links to test cards on testing event pages. Or something like that.

### CODE REVIEW

**Comment by harrislapiroff** [comment]
Got this migration error:

```
django.db.utils.IntegrityError: NOT NULL constraint failed: brambling_person__new.stripe_test_customer_id
```

I think we need a default value on `stripe_test_customer_id`?

**Comment by melinath** [comment]
@harrislapiroff so... is there anything left on this?

**Comment by harrislapiroff** [comment]
I haven't fully tested this. I'll work on that now.

**Comment by harrislapiroff** [comment]
I did some rudimentary testing. I don't feel 100% confident about my coverage, but I can't think of how to be more thorough. I got some weird errors when refunding:

screenshot 2015-01-20 17 43 53

Though maybe refunds should be disallowed in test mode altogether? Although it would be nice to be able to test our refund code, eh...?

Otherwise, that and the bugs I fixed are all I found. Bouncing back to you @melinath.

**Comment by melinath** [comment]
Did you get all those errors at the same time? The first two are probably from Dwolla - their test APIs are kind of terrible - essentially, you can only refund if your dwolla account has money in it. Not sure why you got two, unless the messages got stored up somehow...

**Comment by harrislapiroff** [comment]
I might have hit refund a couple times and they didn't display till I visited a page that had messages in the template. (Also a bug?)

**Comment by harrislapiroff** [comment]
I might also have picked an order that had multiple payments (with different methods) on it

**Pull request merged**
