### PR TITLE
Prevent links from double-posting when double-clicked

### PR DESCRIPTION
**Pull request by chigby**
See #665 for motivation.

This change will stop post requests from firing twice when double-clicked. I am not sure to what extent the site is using the convention of `<a target="...">` to trigger a post, so I hope this doesn't break anything I didn't think of. Ideally, though, this will fix double-clicking in all those places.

### CODE REVIEW

**Comment by melinath** [comment]
This doesn't quite work as-is. When the script runs the first time, it looks for all `a[target]` elements and attaches a listener to them. Removing the target attribute later doesn't remove the handler.

One alternative would be to move the click event up to the body - i.e.:

```javascript
$('body').on('click', 'a[target]', function() {});
```

(You can test by commenting out the post and logging each click event.)

**Comment by chigby** [comment]
Good catch! In my manual testing it did appear to be working, but maybe my double-click finger is rusty. 

One other solution I though of (though I think yours is simpler) would be to add a "clicked" marker to the element that was clicked, then only send the post if the marker isn't there.

**Comment by harrislapiroff** [comment]
What's the status of this branch? Is it ready for review or is it awaiting a solution?

**Comment by melinath** [comment]
It's ready for review.

**Comment by melinath** [comment]
@harrislapiroff just to clarify, this branch works, I just wasn't sure if there might be concerns with the method used.

**Comment by harrislapiroff** [comment]
It's not ideal, I think, but the overloading of `target` to contain URLs is the not ideal part and should be fixed elsewhere I think. Reviewing now.

**Comment by harrislapiroff** [comment]
Actually I have a more elegant way of doing this I think.

**Comment by harrislapiroff** [comment]
Eh, I changed my mind.

**Comment by harrislapiroff** [comment]
I was going to use jQuery's `.one` method, but because we need to `preventDefault` on every click, that doesn't actually work.

**Pull request merged**
